version: '1.0'
kind: step-type
metadata:
  name: globetracker/dynamic-1d-matrix-freestyle
  isPublic: true
  description: |-
    This generates a dynamic 1D matrix of freestyle steps
  sources:
    - 'https://github.com/globe-tracker/cf-step-dynamic-matrix.git'
  stage: incubating
  maintainers:
    - name: Julius Biskopstø
  categories:
    - git
  official: false
  tags: []
  icon:
    type: svg
    url: https://raw.githubusercontent.com/globe-tracker/cf-step-dynamic-matrix/main/locator.svg
    background: '#f4f4f4'
  examples:
    - description: example-1
      workflow:
        version: '1.0'
        steps:
          say_hello:
            title: Running multiple dynamic commands
            type: globetracker/dynamic-1d-matrix-freestyle
            arguments:
              NAME: "say_hello"
              IMAGE: "alpine"
              STAGE: "ci"
              WORKING_DIRECTORY: "${{CF_VOLUME_PATH}}"
              ENVIRONMENT: 
              - "BRANCH=${{CF_BRANCH}}"
              COMMANDS:
              - "echo 'Hello %VALUE% on $BRANCH'"
              VALUES: "project1,project2,project3"
    - description: example-2
      workflow:
        version: '1.0'
        steps:
          say_hello:
            title: Running multiple dynamic commands
            type: globetracker/dynamic-1d-matrix-freestyle
            arguments:
              NAME: "say_hello2"
              IMAGE: "alpine"
              STAGE: "ci"
              COMMANDS:
              - "echo 'Hello %VALUE% on $BRANCH'"
              VALUES: "project1,project2,project3"
              DEPENDS: 
              - "say_hello_step"
  latest: true
  version: 1.0.10
spec:
  arguments: |-
    {
      "definitions": {},
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object",
      "additionalProperties": false,
      "patterns": [],
      "required": [
        "NAME",
        "IMAGE",
        "STAGE",
        "COMMANDS",
        "VALUES"
      ],
      "properties": {
        "NAME": {
          "type": "string",
          "description": "The name of the dynamic steps, index will be added"
        },
        "IMAGE": {
            "type": "string",
            "description": "what image should be used for the steps in the matrix"
        },
        "STAGE": {
            "type": "string",
            "description": "what stage in the pipeline is this matrix running in"
        },
        "COMMANDS": {
            "type": "array",
            "description": "Set the number of "
        },
        "VALUES": {
          "description": "A list/array of index values",
          "type": "string"
        },
        "DEPENDS": {
            "type": "array",
            "description": "list of dependent steps",
            "items": {
              "type": "string"
            }
        },
        "ENVIRONMENT": {
            "type": "array",
            "description": "list of environment variables",
            "items": {
              "type": "string"
            }
        },
        "WORKING_DIRECTORY": {
            "type": "string",
            "description": "working directory"
        }
      }
    }
  delimiters:
    left: '[['
    right: ']]'
  stepsTemplate: |-
    print_info_message:
      name: globetracker-cf/dynamic-matrix
      title: Info message
      image: alpine
      commands:
        - echo "Creating [[ .Arguments.NAME ]], a dynamic 1 dimensional matrix of [[ strings.Split "," .Arguments.VALUES | len ]] values"
    some_parallel_task:
      type: parallel
      stage: [[ .Arguments.STAGE ]]
      steps:
        [[- range $index, $value := strings.Split "," .Arguments.VALUES ]]
        print_info[[ $index ]]:
          title: Info message
          type: freestyle
          image: alpine
          commands:
            - echo "echo [[ $value ]] [[ $.Arguments.NAME ]]"
        [[- end ]]
